# Generated by Django 4.1.7 on 2023-03-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("neighborhood", models.CharField(max_length=100)),
                ("street", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("number", models.IntegerField()),
            ],
        ),
    ]
