# Generated by Django 4.1.7 on 2023-03-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
