# Generated by Django 4.1.7 on 2023-03-07 20:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shopping_carts", "0003_alter_shoppingcarts_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shoppingcarts",
            old_name="product",
            new_name="products",
        ),
    ]
