# Generated by Django 4.1.7 on 2023-03-07 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shopping_carts", "0005_shoppingcartitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shoppingcartitem",
            old_name="products",
            new_name="product",
        ),
    ]
