# Generated by Django 4.1.7 on 2023-03-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_placed", models.BooleanField(default=True)),
                ("order_in_progress", models.BooleanField(default=False)),
                ("order_delivered", models.BooleanField(default=False)),
            ],
        ),
    ]
