# Generated by Django 4.1.7 on 2023-03-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_remove_order_order_delivered_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
        migrations.RemoveField(
            model_name="orderedproduct",
            name="totalPrice",
        ),
        migrations.RemoveField(
            model_name="orderedproduct",
            name="totalQuantity",
        ),
        migrations.AddField(
            model_name="order",
            name="totalPrice",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="order",
            name="totalQuantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
