# Generated by Django 4.1.7 on 2023-03-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_remove_order_products_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderedproduct",
            name="category",
            field=models.CharField(default="aleatorio", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderedproduct",
            name="name",
            field=models.CharField(default="qualquer_um", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderedproduct",
            name="price",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
