# Generated by Django 4.1.7 on 2023-03-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_orderedproduct_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderedproduct",
            name="buyer",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
