# Generated by Django 4.1.7 on 2023-03-06 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="user",
            field=models.ManyToManyField(
                related_name="product", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
