# Generated by Django 4.1.7 on 2023-03-06 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="quantity",
            new_name="stock",
        ),
        migrations.RemoveField(
            model_name="product",
            name="user",
        ),
    ]
