# Generated by Django 4.1.7 on 2023-03-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="img",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
