# Generated by Django 4.1.7 on 2023-03-10 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_product_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="username",
        ),
    ]
