# Generated by Django 4.1.7 on 2023-03-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_alter_product_description_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
